### PR TITLE
Fix #25: Use a stable repository to consume SWTBot

### LINKED ISSUE #25: Use a stable repository to consume SWTBot
Currently the target platform definitions reference the http://download.eclipse.org/technology/swtbot/releases/latest/ repository of SWTBot. Because its contents change with each release the target platform definitions may become stale.

### PR DESCRIPTION
**Pull request by rherrmann**
This commit changes the SWTBot repository to v2.4 for all target platforms 

All test pass except this one (fails on all Eclipse versions):
However, I don't think this is related to a particular SWTBot version. Can anyone figure why this test fails?
```
org.moreunit.swtbot.test
org.moreunit.refactoring.RenameMethodTest
should_rename_corresponding_test_methods_when_method_gets_renamed(org.moreunit.refactoring.RenameMethodTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Text' and with label (with mnemonic 'New name:'))

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:472)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:419)

	at org.eclipse.swtbot.swt.finder.SWTBot.textWithLabel(SWTBot.java:1478)

	at org.eclipse.swtbot.swt.finder.SWTBot.textWithLabel(SWTBot.java:1466)

	at org.moreunit.refactoring.RenameMethodTest.renameMethodAndWaitUntilFinished(RenameMethodTest.java:56)

	at org.moreunit.refactoring.RenameMethodTest.should_rename_corresponding_test_methods_when_method_gets_renamed(RenameMethodTest.java:37)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.moreunit.test.context.TestContextRule$StatementInContext.evaluate(TestContextRule.java:244)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)

	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)

	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)

	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)

	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)

	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:66)

	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:43)

	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness$$Lambda$58/1182904162.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Text' and with label (with mnemonic 'New name:'))

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:466)

	... 35 more



org.moreunit.refactoring.MoveMethodTest
should_move_test_method_when_static_method_gets_moved(org.moreunit.refactoring.MoveMethodTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find shell matching: with text 'Open Resource'

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:472)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shells(SWTBotFactory.java:116)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shell(SWTBotFactory.java:106)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shell(SWTBotFactory.java:97)

	at org.moreunit.JavaProjectSWTBotTestHelper.openResource(JavaProjectSWTBotTestHelper.java:133)

	at org.moreunit.refactoring.MoveMethodTest.should_move_test_method_when_static_method_gets_moved(MoveMethodTest.java:30)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.moreunit.test.context.TestContextRule$StatementInContext.evaluate(TestContextRule.java:244)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)

	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)

	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)

	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)

	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)

	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:66)

	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:43)

	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness$$Lambda$58/1182904162.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find shell matching: with text 'Open Resource'

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)

	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:466)

	... 35 more

```

### CODE REVIEW

**Comment by ndemengel** [comment]
Those tests pass on my machine, but some other don't:

```
Failed tests:   should_jump_to_cut_when_shortcut_is_pressed_in_testcase(org.moreunit.jump.BasicJumpTest): expected:<'SomeClass[].java'> but was:<'SomeClass[Test].java'>
  should_jump_from_method_to_test_method(org.moreunit.jump.BasicJumpTest): expected:<[7]> but was:<[6]>
  should_jump_to_test_when_shortcut_is_pressed_in_cut(org.moreunit.jump.BasicJumpTest): expected:<'SomeClass[Test].java'> but was:<'SomeClass[].java'>
  should_jump_to_test_when_two_test_exist_but_one_is_prefect_match(org.moreunit.jump.BestMatchJumpTest): expected:<'SomeClass[Test].java'> but was:<'SomeClass[].java'>
  should_show_choose_dialog_when_two_tests_exists_and_no_perfect_match_exists(org.moreunit.jump.BestMatchJumpTest): expected:<[4]> but was:<[1]>
```

We already had a time previously when the SWTBot tests were brittle. Maybe it is related to the version of SWTBot, or maybe those tests are not well written.

At least we can run them now, so let's merge this pull request.

**Comment by rherrmann** [comment]
Thanks Nicolas, for merging the changes. 
I've also seen some test failing occasionally. Several tests use _Open Resource_ followed by typing the class name in order to open an editor. And - among others - I've seen this process getting stuck. Maybe opening the editor could be replaced with something along these lines:
```java
Display display = Display.getDefault(); // or obtain display from elsewhere
display.syncExec( () -> IDE.openEditor( ... ) );
```
That would certainly not cure every hickup, but it might be a start.

**Comment by gianasista** [comment]
I am a little biased about the SWTBot tests. They seem to be error prone and hard to maintain. Using the above code is a starting point to reduce the risk of failing tests. Any ideas how this could be improved are very welcome, perhaps there is a better tool already?

**Comment by apupier** [comment]
I almost finished fixing it but I have to go right now. Hope to push it this evening or tomorrow

**Comment by apupier** [comment]
see https://github.com/MoreUnit/MoreUnit-Eclipse/pull/27

@gianasista Personally, I think that SWTbot is quite good. Most of issues that we encounter due to asyncrhonism will be encountered in other testing framework. But if we really want to try a new one, i would suggest Jubula http://www.eclipse.org/jubula/

**Comment by gianasista** [comment]
@apupier When Jubula came up I took a short look at it. It looks good but what made me stay with SWTBot was that this is pure Java and much easier for developers/contributors to understand. Do you have experience with Jubula?

**Comment by apupier** [comment]
@gianasista only followed a tutorial long time ago. They now provide a Java API: https://www.eclipse.org/community/eclipse_newsletter/2015/july/article3.php

**Pull request merged**
